version: 2

sources:
    - name: schema
      description: This is a replica of the snowflake database used by our app
      database: SOURCE
      schema: STUDENT_SOURCE
      tables:
          - name: studentmarks
            description: One record per student.
